baseURL = "https://serials.vev.su/"
title = "Сериалы"
defaultContentLanguage = "ru"
languageCode = "ru-ru"
publishdir = "./docs"

[params]
  subtitle = "Подборки сериалов"
  description = "Советуем, что и как смотреть"
  googleTagManagerId = "GTM-M5HZVHN"
  storageMedia = "https://ams.su"
